SELECT MSISDN,
    IMEI_TAC,
    COALESCE(BRAND_NAME,'UNKNOWN') AS BRAND_NAME,
    COALESCE(MODEL_NAME,'UNKNOWN') AS MODEL_NAME,
    COALESCE(OS_NAME,'UNKNOWN') AS OS_NAME,
    COALESCE(OS_VENDOR,'UNKNOWN') AS OS_VENDOR
    FROM GOOD_YEAR.RAW.DEVICE