select A.*,B.WEEK_NUMBER,B.REVENUE_USD,C.IMEI_TAC,C.BRAND_NAME,C.MODEL_NAME,C.OS_NAME,C.OS_VENDOR
from  {{ref('C_CRM')}} A
JOIN  {{ref('C_REV')}} B ON A.MSISDN=B.MSISDN
JOIN  {{ref('C_DEVICE')}} C ON A.MSISDN=C.MSISDN